### ISSUE TITLE
Disable some items

### ISSUE THREAD

**Issue by nihas** [dvdciri/MultiChoiceRecyclerView#17]
How can i disable some items in the recyclerview to select

**Comment by dvdciri** [comment]
What do you mean by "disable some items .. to select"?

**Comment by dvdciri** [comment]
Last call, please give more info (use the issue template) otherwise it'll be sadly closed. =(

**Comment by nihas** [comment]
As i dont want some items to be selected. how can i achieve that

**Comment by dvdciri** [comment]
You want to disable some item from the multi choice selection in order to get just the normal click listener and not the selection one.

I can add a method to disable some item from and not apply the selection mode on them but just keep the normal click listener if implemented `MultiChoiceAdapter#defaultItemViewClickListener(...)`, is that good for you?

**Comment by nihas** [comment]
yeahhh its fine for me... thank you..

**Comment by dvdciri** [comment]
This is now in develop and will be available in the new release v1.2.14
