### ISSUE TITLE
Selected item background color and text color

### ISSUE THREAD

**Issue by sagar15795** [dvdciri/MultiChoiceRecyclerView#3]
How can i change selected item background color and text color

**Comment by dvdciri** [comment]
If you read the README file, there is a bit that explains of to customize it. You have to override the setActive method of the MultiChoiceAdapter. At that point you can customize your view in relation to the state.

```java
    @Override
    public void setActive(View view, boolean state) {
        if(state){
            //do your changes
        }else{
            //reset the changes
        }
    }
```

The View parameter is the root of your layout item, i know that from that one you'll need to use complicated stuff to customize the layout 100% and maybe loop through childs and find the right one, but i'm working on the customisation bit in order to make it easier. (You'll probably just need to use findViewById but i can't ensure that i'll work on everything)

**Comment by dvdciri** [comment]
@sagar15795  If you've got any suggestion or enhancement fell free to pull request it.
Thanks

**Comment by sagar15795** [comment]
Thanks
